# Generated by Django 5.1.3 on 2024-11-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "chest_pain",
                    models.CharField(
                        choices=[
                            ("ATA", "Atypical Angina"),
                            ("NAP", "Non-Anginal Pain"),
                            ("ASY", "Asymptomatic Pain"),
                            ("TA", "Typical Angina"),
                        ],
                        max_length=3,
                    ),
                ),
                ("resting_bp", models.IntegerField()),
                ("cholesterol", models.IntegerField()),
                ("fasting_bs", models.IntegerField(choices=[(0, "0"), (1, "1")])),
                (
                    "resting_ecg",
                    models.CharField(
                        choices=[("Normal", "Normal"), ("ST", "ST"), ("LVH", "LVH")],
                        max_length=10,
                    ),
                ),
                ("max_heart_rate", models.IntegerField()),
                (
                    "exercise_angina",
                    models.CharField(choices=[("N", "No"), ("Y", "Yes")], max_length=1),
                ),
                ("old_peak", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "st_slope",
                    models.CharField(
                        choices=[("Up", "Up"), ("Flat", "Flat"), ("Down", "Down")],
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
